version: "3.9"

services:
  snd-server:
    image: soundations-snd-server:latest
    restart: unless-stopped
    environment:
      - SND_SERVER_HOST=${SND_SERVER_HOST:-0.0.0.0}
      - SND_SERVER_PORT=${SND_SERVER_PORT:-6660}
      - SND_SQLITE_DB_PATH=////opt/soundations-data/snd-server-main.sqlite
    build:
      context: ./
      dockerfile: ./snd-server/Dockerfile.prod
    volumes:
        - /opt/soundations-data:/opt/soundations-data
    ports:
      - 6660:6660
