version: "3.9"

services:
  snd-server:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./snd-server/Dockerfile
    volumes:
        - ./snd-server:/snd-server
    entrypoint:
      - /bin/sh
      - -c
      - |
        uvicorn main:app --reload --host 0.0.0.0 --port 6660

    ports:
      - 6660:6660
