version: "3.9"

services:
  snd-server:
    image: soundations-snd-server:latest
    restart: unless-stopped
    environment:
      - SND_SERVER_HOST=${SND_SERVER_HOST:-0.0.0.0}
      - SND_SERVER_PORT=${SND_SERVER_PORT:-6660}
      - SND_SQLITE_DB_PATH=////opt/soundations-data/snd-server-main.sqlite
      - SND_RECOMMENDER_ARCHIVE_PATH=/soundations/snd-server/recommender_model.zip
      - SND_SPOTIFY_CLIENT_ID=${SND_SPOTIFY_CLIENT_ID:-dummy_spotify_client_id}
      - SND_SPOTIFY_CLIENT_SECRET=${SND_SPOTIFY_CLIENT_SECRET:-dummy_spotify_client_secret}
    build:
      context: ./
      dockerfile: ./snd-server/Dockerfile.prod
    volumes:
        - /opt/soundations-data:/opt/soundations-data
    ports:
      - 6660:6660

  snd-proxy:
    depends_on:
      - snd-server
    image: soundations-snd-proxy:latest
    restart: unless-stopped
    environment:
      - SND_SERVER_HOST=snd-server
      - SND_SERVER_PORT=${SND_SERVER_PORT:-6660}
    build:
      context: ./
      dockerfile: ./snd-proxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
