FROM python:3.11.0-slim

RUN pip install 'poetry==1.2.2'

WORKDIR /soundations

COPY ./pyproject.toml \
  ./poetry.toml \
  ./poetry.lock \
  /soundations/

COPY ./.venv /soundations/.venv/
COPY ./snd-server /soundations/snd-server/
COPY ./bin /soundations/bin/

ENTRYPOINT [ "./bin/start-server-prod.sh" ]
