name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker builder cache
      id: docker-builder-cache
      uses: actions/cache@v3
      with:
        path: docker-builder-cache
        key: ${{ runner.os }}-docker-builder-cache-${{ hashFiles('Dockerfile.builder') }}

    - name: Build docker builder image
      if: steps.docker-builder-cache.outputs.cache-hit != 'true'
      run: ./bin/build-docker-builder.sh && ./bin/save-docker-builder.sh > docker-builder-cache

    - name: Load docker builder image
      run: docker load < docker-builder-cache

    - name: Install dependencies
      run: ./bin/docker-run.sh ./bin/install.sh

    - name: Lint source code
      run: ./bin/docker-run.sh ./bin/lint.sh
